# run: conda env create --file environment.yml
# run: conda env create python=3.6 --file environment.yml
# include new packages: conda env update --file environment.yml
name: carcasonne
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.19
  - pytest
  - networkx
  - matplotlib
  - pip
  - pip:
    - black